name: "BIS Tracker (robust + budgeted: delta + full HTML)"

'on':
  schedule:
    - cron: '0 3 * * 1'   # Mondays ~06:00 Riga time (03:00 UTC)
  workflow_dispatch: {}

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Scrape (robust, time-boxed)
        env:
          # Depth & pacing
          PAGES_TOTAL: "5000"
          PAGE_ORDER_MODE: "strided"     # "sequential" or "strided"
          STRIDE: "800"                   # only for "strided"
          PAGE_DELAY_MS: "100"
          # Error handling
          MAX_RETRIES_PER_PAGE: "2"
          RETRY_BASE_MS: "1200"
          EMPTY_PAGE_TOLERANCE: "2"
          ERROR_BAIL_WINDOW: "80"
          ERROR_BAIL_THRESHOLD: "0.75"
          # Time budget (minutes)
          GLOBAL_MINUTES_BUDGET: "75"
          # Context rotation
          CONTEXT_ROTATE_EVERY: "350"
        run: |
          python scraper.py

      - name: Upload debug (first pages + error/empty markers)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-pages
          path: debug
          if-no-files-found: ignore

      - name: Commit state + reports
        run: |
          git config user.name "bis-bot"
          git config user.email "bis-bot@users.noreply.github.com"
          git add state/state.json reports/report_*.html || true
          git commit -m "Snapshot & reports: $(date -u +'%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          git push

      - name: Email reports (HTML only)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # e.g., smtp.gmail.com
          server_port: ${{ secrets.SMTP_PORT }}        # 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: BIS tracker — atskaite ${{ github.run_id }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: false            # 587 with STARTTLS (no 'starttls' key)
          html_body: |
            <p>Sveiki! Pievienotas atskaites:</p>
            <ul>
              <li><code>report_delta.html</code> – tikai jauni ieraksti un stadiju izmaiņas</li>
              <li><code>report_full.html</code> – pilns momentuzņēmums (visi atlasītie ieraksti no šī skrējiena)</li>
            </ul>
            <p><small>Ja serveris bieži atgriež 503, skrējiens tiek laipni pārtraukts pirms 6h limīta un saglabā daļējus rezultātus.</small></p>
          attachments: |
            reports/report_delta.html
            reports/report_full.html
