name: BIS Tracker (delta-only, HTML email)

on:
  schedule:
    - cron: "0 3 * * 1"   # Mondays ~06:00 Riga summer / ~05:00 winter (as before)
  workflow_dispatch: {}

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Scrape (direct URL pagination; delta-only output)
        env:
          PAGES_TOTAL: "5000"       # you can lower/raise anytime
          PAGE_DELAY_MS: "25"       # courtesy; set "0" if you want max speed
        run: |
          python scraper.py

      - name: Upload debug HTML (first 2 pages)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-pages
          path: debug
          if-no-files-found: ignore

      - name: Commit state + report
        run: |
          git config user.name "bis-bot"
          git config user.email "bis-bot@users.noreply.github.com"
          git add state/state.json reports/report.html || true
          git commit -m "Snapshot & delta: $(date -u +'%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          git push

      - name: Email report (HTML only)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # smtp.gmail.com
          server_port: ${{ secrets.SMTP_PORT }}        # 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: BIS tracker — izmaiņu atskaite ${{ github.run_id }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: false            # 587 with STARTTLS (no starttls key)
          html_body: |
            <p>Sveiki! Pielikumā šī skrējiena <strong>izmaiņu</strong> atskaite (tikai jauni / stadijas izmaiņas).</p>
            <p>Ja pielikums nav atvērts, to var apskatīt arī repozitorijā: <code>reports/report.html</code>.</p>
          attachments: |
            reports/report.html
