name: BIS Tracker (weekly deep + email)

on:
  schedule:
    - cron: "0 3 * * 1"   # Mondays ~06:00 Riga summer / ~05:00 winter
  workflow_dispatch: {}

jobs:
  deep_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Scrape (weekly, with page cap)
        env:
          LANG: "lv"
          MAX_PAGES_PER_COMBO: "50"         # ← you can raise/lower this
          MAX_PAGES_HARD_CAP: "50"          # keep equal to enforce the cap hard
        run: |
          python scraper.py

      - name: Commit reports
        run: |
          git config user.name "bis-bot"
          git config user.email "bis-bot@users.noreply.github.com"
          git add reports/*.csv reports/CHANGELOG.md || true
          git commit -m "Weekly scan: $(date -u +'%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          git push

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: BIS weekly tracker – report ${{ github.run_id }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: true
          html_body: |
            <p>Sveiki!</p>
            <p>Šonedēļas rezultāti ir ģenerēti un pievienoti mapē <code>reports/</code>.</p>
            <ul>
              <li><code>CHANGELOG.md</code> – kopsavilkums (pielikumā)</li>
              <li><code>latest.csv</code> – pilns momentuzņēmums (pielikumā)</li>
            </ul>
            <p>Parametri: lapu limits katrai kombinācijai = ${{ env.MAX_PAGES_PER_COMBO }}; valoda = ${{ env.LANG }}.</p>
          attachments: |
            reports/CHANGELOG.md
            reports/latest.csv
