name: BIS Tracker (delta + full HTML)

on:
  schedule:
    - cron: "0 3 * * 1"   # Mondays ~06:00 Riga summer / ~05:00 winter
  workflow_dispatch: {}

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Scrape (direct URL pagination)
        env:
          PAGES_TOTAL: "5000"          # raise/lower freely
          PAGE_DELAY_MS: "25"          # set "0" for max speed
          EMPTY_PAGE_TOLERANCE: "3"    # consecutive empty pages before stopping
        run: |
          python scraper.py

      - name: Upload debug HTML (first pages + empties)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-pages
          path: debug
          if-no-files-found: ignore

      - name: Commit state + reports
        run: |
          git config user.name "bis-bot"
          git config user.email "bis-bot@users.noreply.github.com"
          git add state/state.json reports/report_*.html || true
          git commit -m "Snapshot & reports: $(date -u +'%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          git push

      - name: Email reports (HTML only)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # smtp.gmail.com
          server_port: ${{ secrets.SMTP_PORT }}        # 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: BIS tracker — atskaite ${{ github.run_id }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: false            # 587 with STARTTLS (no 'starttls' key)
          html_body: |
            <p>Sveiki! Pievienotas atskaites:</p>
            <ul>
              <li><code>report_delta.html</code> – tikai jauni ieraksti un stadiju izmaiņas</li>
              <li><code>report_full.html</code> – pilns momentuzņēmums (visi atlasītie ieraksti)</li>
            </ul>
          attachments: |
            reports/report_delta.html
            reports/report_full.html
