name: BIS Tracker (weekday 06:00 Riga)

on:
  schedule:
    # GitHub Actions uses UTC. Riga is UTC+3 in summer (approx 06:00 = 03:00 UTC)
    # and UTC+2 in winter (approx 06:00 = 04:00 UTC).
    # We'll run at 03:00 UTC Mon–Fri. In winter this will be 05:00 Riga.
    - cron: "0 3 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Scrape & build report
        run: python scraper.py

      - name: Commit reports
        run: |
          git config user.name "bis-bot"
          git config user.email "bis-bot@users.noreply.github.com"
          git add reports/*.csv reports/CHANGELOG.md || true
          git commit -m "Update: $(date -u +'%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          git push
