name: BIS Tracker (single job, local parsing)

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch: {}

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Scrape (local parsing)
        env:
          PAGES_TOTAL: "30"
        run: |
          python scraper.py

      - name: Upload debug HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-pages
          path: debug
          if-no-files-found: ignore

      - name: Commit reports
        run: |
          git config user.name "bis-bot"
          git config user.email "bis-bot@users.noreply.github.com"
          git add reports/*.csv reports/CHANGELOG.md || true
          git commit -m "Snapshot: $(date -u +'%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          git push

      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # smtp.gmail.com
          server_port: ${{ secrets.SMTP_PORT }}        # 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: BIS tracker — snapshot ${{ github.run_id }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: false         # <-- IMPORTANT for 587
          starttls: true        # <-- use STARTTLS
          html_body: |
            <p>Sveiki! Pievienota šodienas momentuzņēmuma atskaite.</p>
            <ul>
              <li><code>CHANGELOG.md</code> – kopsavilkums (pielikumā)</li>
              <li><code>latest.csv</code> – pilns momentuzņēmums (pielikumā)</li>
            </ul>
          attachments: |
            reports/CHANGELOG.md
            reports/latest.csv
